language: node_js
node_js:
  - "0.11"
notifications:
  email: false
install:
 - npm install jshint -g
 - npm install codeclimate-test-reporter -g
script:
 - jshint autoPlay.user.js
 - codeclimate < lcov.info
